services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - redis
    environment:
      APP_URL: ${APP_URL}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: "redis://redis:6379"
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  redis_data:
